# https://github.com/meteorhacks/meteord
FROM  abernix/meteord:onbuild

# The maintainer of your app image
MAINTAINER Mauricio Oporto <fmod@the-dsw.com>

# (optional) Bake runtime options into your image
# ENV MONGO_URL="mongodb://url" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://yourapp.com"


