# https://github.com/meteorhacks/meteord
FROM meteorhacks/meteord:devbuild

# The maintainer of your app image
MAINTAINER epflsti <stiitscm@groupes.epfl.ch>

# (optional) Bake runtime options into your image
# ENV MONGO_URL="mongodb://url" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://yourapp.com"
